import type { Service } from "@/types";

export const services: Service[] = [
  {
    id: "fade",
    name: "Fade",
    description:
      "Difuminado perfecto con degradado impecable, perfilado con navaja y estilo final.",
    duration: 50,
    price: 320,
    image: "/images/services/fade.jpg",
    alt: "Barbero realizando un fade con máquina en la nuca de un cliente",
    featured: true,
    badge: "Más pedido",
  },
  {
    id: "low-fade",
    name: "Low Fade",
    description: "Difuminado que inicia a baja altura, ideal para estilos clásicos y sobrios.",
    duration: 45,
    price: 300,
    image: "/images/services/low-fade.jpg",
    alt: "Barbero recortando cabello con tijera para un low fade",
  },
  {
    id: "mid-fade",
    name: "Mid Fade",
    description: "El equilibrio perfecto entre modernidad y versatilidad para cualquier estilo.",
    duration: 45,
    price: 300,
    image: "/images/services/mid-fade.jpg",
    alt: "Navaja deslizando sobre un mid fade en barbería",
  },
  {
    id: "high-fade",
    name: "High Fade",
    description: "Degradado alto con máximo contraste. El favorito de los looks urbanos.",
    duration: 50,
    price: 320,
    image: "/images/services/high-fade.jpg",
    alt: "Máquina recortando un high fade en la parte trasera de la cabeza",
  },
  {
    id: "corte-clasico",
    name: "Corte Clásico",
    description: "Corte tradicional con tijera y navaja, refinado con técnica atemporal.",
    duration: 40,
    price: 280,
    image: "/images/services/corte-clasico.jpg",
    alt: "Barbero profesional dando un corte clásico a un cliente",
  },
  {
    id: "corte-ejecutivo",
    name: "Corte Ejecutivo",
    description: "Precisión y elegancia para el hombre de negocios. Listo en 30 minutos.",
    duration: 30,
    price: 260,
    image: "/images/services/corte-ejecutivo.jpg",
    alt: "Barbero peinando un corte ejecutivo a un cliente en la silla",
  },
  {
    id: "barba",
    name: "Barba",
    description: "Diseño, recorte y armonía de tu barba según la forma de tu rostro.",
    duration: 30,
    price: 200,
    image: "/images/services/barba.jpg",
    alt: "Cliente recibiendo un recorte de barba con precisión",
  },
  {
    id: "afeitado",
    name: "Afeitado Tradicional",
    description: "Navaja recta, toalla caliente y espuma al estilo de la barbería clásica.",
    duration: 30,
    price: 240,
    image: "/images/services/afeitado.jpg",
    alt: "Navaja recta y equipo de afeitado tradicional en barbería",
    badge: "Premium",
  },
  {
    id: "perfilado",
    name: "Perfilado",
    description: "Detalle fino con navaja para definir entradas, patillas y cuello.",
    duration: 20,
    price: 150,
    image: "/images/services/perfilado.jpg",
    alt: "Barbero peinando y perfilando el cabello con precisión",
  },
  {
    id: "lavado",
    name: "Lavado",
    description: "Lavado relajante con productos premium que restauran tu cuero cabelludo.",
    duration: 20,
    price: 120,
    image: "/images/services/lavado.jpg",
    alt: "Lavado de cabello profesional en un salón moderno",
  },
  {
    id: "mascarilla",
    name: "Mascarilla",
    description: "Tratamiento capilar de hidratación profunda con productos de alta gama.",
    duration: 30,
    price: 180,
    image: "/images/services/mascarilla.jpg",
    alt: "Productos de barbería premium sobre la mesa de un salón vintage",
  },
  {
    id: "paquete-premium",
    name: "Paquete Premium",
    description: "La experiencia completa: corte, barba, lavado, toalla caliente y bebida.",
    duration: 90,
    price: 550,
    image: "/images/services/paquete-premium.jpg",
    alt: "Barberos profesionales atendiendo clientes en una barbería tradicional",
    featured: true,
    badge: "Experiencia completa",
  },
];

export const serviceCategories = [
  {
    id: "cortes",
    label: "Cortes",
    description: "Fades y cortes de precisión",
  },
  {
    id: "barba",
    label: "Barba",
    description: "Recorte, perfilado y afeitado",
  },
  {
    id: "bienestar",
    label: "Bienestar",
    description: "Lavado, mascarillas y rituales",
  },
] as const;
